#!/bin/sh
# Installs the ai-attribution CLI and hooks without requiring Claude Code.
#
# Claude Code students get this plugin through `claude plugin install`, which
# also registers hooks/hooks.json so Claude Code fires it automatically. No
# other agent has an equivalent registration step -- `aiattr install-hooks
# <tool>` does that job for them instead -- so this script's only job is
# getting the files onto disk at a fixed, predictable path. Fixed matters for
# the same reason core/paths.py keeps the data directory fixed: a path that
# can move silently orphans a student's setup later.
#
# Usage:
#   curl -fsSL .../install.sh | sh
#   curl -fsSL .../install.sh | sh -s -- --key b2b_xxx --endpoint https://...
#
# Passing --key/--endpoint runs `configure` for you, so the whole setup is one
# command the dashboard can hand over with the key already filled in. That is
# also why this file is POSIX sh with a /bin/sh shebang rather than bash: it is
# almost always executed as `sh -s`, where the shebang is never consulted and
# bashisms would fail on a dash /bin/sh.
#
# Safe to re-run: it replaces whatever was at the install directory, which is
# how updating works -- run it again to pick up a newer version.

set -eu

REPO_URL="${AIATTR_REPO_URL:-https://github.com/K-man1/b2b-hook}"
BRANCH="${AIATTR_BRANCH:-main}"
INSTALL_DIR="${AIATTR_INSTALL_DIR:-$HOME/.ai-attribution/plugin}"
BIN_DIR="${AIATTR_BIN_DIR:-$HOME/.ai-attribution/bin}"

KEY=""
ENDPOINT=""

while [ $# -gt 0 ]; do
  case "$1" in
    --key) KEY="${2:-}"; shift 2 ;;
    --key=*) KEY="${1#*=}"; shift ;;
    --endpoint) ENDPOINT="${2:-}"; shift 2 ;;
    --endpoint=*) ENDPOINT="${1#*=}"; shift ;;
    -h|--help)
      echo "usage: install.sh [--key KEY] [--endpoint URL]"
      exit 0 ;;
    *)
      echo "install.sh: unknown option '$1'" >&2
      exit 1 ;;
  esac
done

for bin in curl tar; do
  command -v "$bin" >/dev/null 2>&1 || {
    echo "error: $bin is required and was not found on PATH." >&2
    exit 1
  }
done

# Which interpreter the shim will find. Probed here too, so a machine with no
# usable Python fails now with an explanation rather than later with silence.
# The probe is `-c ""` rather than `--version` because on Windows `python3` is
# usually the Microsoft Store stub, which prints a version and then exits 49
# in a non-TTY subprocess. Only actually running code tells the two apart.
PYTHON=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 &&
     "$candidate" -c 'import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)' \
       >/dev/null 2>&1; then
    PYTHON="$candidate"
    break
  fi
done
if [ -z "$PYTHON" ] && command -v py >/dev/null 2>&1 && py -3 -c "" >/dev/null 2>&1; then
  PYTHON="py -3"
fi
if [ -z "$PYTHON" ]; then
  echo "error: no working Python 3 found (tried python3, python, py -3)." >&2
  echo "       Install Python 3 from https://python.org and re-run this." >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "Downloading ai-attribution ($BRANCH)..."
curl -fsSL "$REPO_URL/archive/refs/heads/$BRANCH.tar.gz" | tar xz -C "$tmp"

# GitHub's tarball extracts to a single "<repo>-<branch>/" directory, whatever
# its exact name -- found rather than hardcoded so a fork under a different
# name still works with AIATTR_REPO_URL overridden.
extracted="$(find "$tmp" -mindepth 1 -maxdepth 1 -type d | head -n 1)"
if [ -z "$extracted" ] || [ ! -f "$extracted/cli/aiattr.py" ]; then
  echo "error: download did not produce a usable plugin directory." >&2
  exit 1
fi

mkdir -p "$(dirname "$INSTALL_DIR")"
rm -rf "$INSTALL_DIR"
mv "$extracted" "$INSTALL_DIR"

# A launcher, so nothing downstream ever has to name an interpreter. The
# dashboard used to print `python3 <path>` commands, which broke on any machine
# where Python 3 is called something else -- and re-detecting per command would
# have put that whole loop in every copy-pasteable line. Resolving it once, in
# a file, is what makes the printed commands short AND correct.
#
# Detection is repeated inside the shim rather than baked in as the interpreter
# found above, because the two run at different times: a student who later
# uninstalls the exact python we found should get a clear error from a shim
# that re-looks, not a stale absolute path failing with "no such file".
mkdir -p "$BIN_DIR"
shim="$BIN_DIR/aiattr"
cat > "$shim" <<EOF
#!/bin/sh
# Generated by install.sh. Runs the ai-attribution CLI with whatever Python 3
# this machine actually has.
CLI="$INSTALL_DIR/cli/aiattr.py"
EOF
cat >> "$shim" <<'EOF'

# PEP 540. Without it, Windows Python picks cp1252 for filesystem encoding and
# crashes on any path containing CJK/Arabic/Hebrew characters.
PYTHONUTF8=1
PYTHONIOENCODING=utf-8
export PYTHONUTF8 PYTHONIOENCODING

for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 &&
     "$candidate" -c 'import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)' \
       >/dev/null 2>&1; then
    exec "$candidate" "$CLI" "$@"
  fi
done

if command -v py >/dev/null 2>&1 && py -3 -c "" >/dev/null 2>&1; then
  exec py -3 "$CLI" "$@"
fi

echo "ai-attribution: no working Python 3 found on PATH." >&2
echo "  Install Python 3 from https://python.org, then re-run this command." >&2
exit 1
EOF
chmod +x "$shim"

echo "Installed to $INSTALL_DIR"

if [ -n "$KEY" ] || [ -n "$ENDPOINT" ]; then
  echo "Connecting this machine to your account..."
  # Built as positional params rather than a string, so a key or endpoint is
  # passed as exactly one argument no matter what is in it. Plain `if`s, not
  # `[ ... ] && ...`: under `set -e` a false test as the whole command is a
  # failing command, which would abort the install.
  set -- configure
  if [ -n "$KEY" ]; then set -- "$@" --key "$KEY"; fi
  if [ -n "$ENDPOINT" ]; then set -- "$@" --endpoint "$ENDPOINT"; fi
  # Hackatime reporting reads the key already in ~/.wakatime.cfg and is a no-op
  # without one, so turning it on unconditionally costs nothing and saves the
  # student a second command they would otherwise have to be told about.
  set -- "$@" --enable-hackatime
  "$shim" "$@"
  echo
  echo "Done. Next, inside each project folder you build in, run:"
  echo "  $shim install-hooks <your-app>"
  echo "  ($shim install-hooks list  shows the supported names)"
else
  echo
  echo "Connect it to your account -- your dashboard shows this with your key"
  echo "already filled in:"
  echo "  $shim configure --key YOUR_KEY --endpoint YOUR_ENDPOINT --enable-hackatime"
  echo
  echo "Then, inside each project folder you build in:"
  echo "  $shim install-hooks <your-app>"
fi

echo
echo "Optional shortcut -- add to ~/.zshrc or ~/.bashrc:"
echo "  export PATH=\"$BIN_DIR:\$PATH\""
